### ISSUE TITLE
Peer-to-peer Code Review

### ISSUE THREAD

**Issue by gvgesanto2** [ulisesedu7/Project-1-Mobile-Skeleton#12]
## Hi @ulisesedu7 👋,

Your project is very good, congrats!

## To Highlight 💯 
✔️ Good UI design
✔️ Good use of Flexbox
✔️ Descriptive class names and JS variables

## Suggestions

- Please for the ``alt`` attribute used in the ``<img>`` tags try to give a value that describes the image's meaning instead of the image's content. This is for accessibility purposes
- Please avoid using fixed height and width lengths for containers. Even though this is not a rule (there are use cases where fixed width and height lengths might be recommended), it can make your life easier in making your webpage responsive
- Please try to use relative length units (e.g. rem, em, vw, vh) instead of absolute length units  (e.g. px). This will make working on your webpage responsiveness an easier job for you.

**Comment by ulisesedu7** [comment]
Thanks!
